# Run command mamba env create -f environment.yml to install all necessary packages
name: lsm-run-time-enhancement
channels:
    - conda-forge
    - nvidia
    - pytorch
    - defaults
dependencies:
    - python=3.11
    - scikit-image
    - matplotlib
    - pytorch 
    - torchvision 
    - cudatoolkit=11.3
    - pandas
    - tqdm
    - tensorboard
    - pip
    - pip:
        - pyyaml
        - pycromanager
        - pytorch-fid

    